// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using core8_ember_oracle.Helpers;

#nullable disable

namespace core8_ember_oracle.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("core8_ember_oracle.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("AlertStocks")
                        .HasColumnType("number(5)")
                        .HasColumnName("alertstocks");

                    b.Property<string>("Category")
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("category");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costprice");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<short>("CriticalStocks")
                        .HasColumnType("number(5)")
                        .HasColumnName("criticalstocks");

                    b.Property<string>("Descriptions")
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("descriptions");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("productpicture");

                    b.Property<short>("Qty")
                        .HasColumnType("number(5)")
                        .HasColumnName("qty");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("saleprice");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sellprice");

                    b.Property<string>("Unit")
                        .HasColumnType("varchar2(10)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("Id");

                    b.ToTable("Products", "C##REY");
                });

            modelBuilder.Entity("core8_ember_oracle.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar2(10)")
                        .HasColumnName("firstname");

                    b.Property<byte>("IsActivated")
                        .HasColumnType("number(2)")
                        .HasColumnName("isactivated");

                    b.Property<byte>("Isblocked")
                        .HasColumnType("number(2)")
                        .HasColumnName("isblocked");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar2(10)")
                        .HasColumnName("lastname");

                    b.Property<short>("Mailtoken")
                        .HasColumnType("number(5)")
                        .HasColumnName("mailtoken");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar2(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("password");

                    b.Property<string>("Profilepic")
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("profilepic");

                    b.Property<string>("Qrcodeurl")
                        .HasColumnType("varchar2(900)")
                        .HasColumnName("qrcodeurl");

                    b.Property<string>("Roles")
                        .HasColumnType("varchar2(10)")
                        .HasColumnName("roles");

                    b.Property<string>("Secretkey")
                        .HasColumnType("varchar2(900)")
                        .HasColumnName("secretkey");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar2(10)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Users", "C##REY");
                });
#pragma warning restore 612, 618
        }
    }
}
